name: ci

on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run fmt
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        
      - name: Install clippy
        run: cargo install clippy --force

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    needs: [fmt, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release
  